### ISSUE TITLE
Support for Sponsoring the Project or devs

### ISSUE THREAD

**Issue by JackPala** [einsteinx2/iSub3#94]
It is clear that this the best Subsonic API compatible app for iOS. My wife loves it for her collection of more esoteric songs that are not conventionally findable on spotify.

But the appears to be no option to sponser the project on github? I'd love to throw a couple bucks your way via github sponsor to say thanks!

**Comment by einsteinx2** [comment]
Apologies for the late response, I had taken a break from working on iSub for a while and am just now seeing all of these community created Github issues (previously I had just used the issues for my own project tracking as no one really interacted with the Github repo since I open sourced it until recently).

For now, while I am actively working on the app again, I don't feel comfortable enabling sponsorships as in the past I have not been super consistent with my focus on the project and I don't feel right taking people's money for it anymore.

If I stay consistent this time and get the new Swift version out, I'll enable sponsorships on Github and some kind of donation feature from within the app.
